# Generated by Django 5.1 on 2024-08-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_account_alter_invoice_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
