# Generated by Django 5.0.7 on 2024-08-26 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('due_date', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.category')),
            ],
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.payable')),
            ],
        ),
    ]
