# Generated by Django 5.0.7 on 2024-08-25 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('type_of_entry', models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense'), ('FIX', 'Fixed Expense')], max_length=3)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bank')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.category')),
            ],
        ),
    ]
