# Generated by Django 5.1 on 2024-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type_of_entry',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense'), ('FIX', 'Fixed Expense')], max_length=3),
        ),
    ]
