# Generated by Django 5.0.7 on 2024-08-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='balance',
        ),
    ]
